---
- name: Tomcat deployment playbook
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
  
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat
      createhome: no
      system: yes

  - name: create /usr/share/ tomcat directory
    file:
      path: /usr/share/tomcat
      state: directory

  - name: Download Tomcat
    get_url: 
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.8/bin/apache-tomcat-8.5.8.tar.gz 
      dest: /opt/apache-tomcat-8.5.8.tar.gz

  - name: Extract archive
    unarchive:
      src: /opt/apache-tomcat-8.5.8.tar.gz
      dest: /usr/share/tomcat
      owner: tomcat
      group: tomcat
      remote_src: yes
      extra_opts: "--strip-components=1"
      creates: /usr/share/tomcat/bin

  - name: Copy Tomcat service from local to remote
    template:
      src: templates/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service

  - name: Start and enable Tomcat service
    service:
      daemon_reload: yes
      name: tomcat
      state: started
      enabled: yes